# Generated by Django 4.1.7 on 2023-03-09 16:40

from django.db import migrations, models
import django.db.models.deletion
import web_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        default=web_auth.models.get_token, max_length=255, unique=True
                    ),
                ),
                ("nbf", models.DateTimeField()),
                ("iat", models.DateTimeField()),
                ("exp", models.DateTimeField()),
                ("is_expired", models.BooleanField(default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "refresh_token",
            },
        ),
    ]
