# Generated by Django 4.1.7 on 2023-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.TextField()),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "admin"), ("user", "user")], max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("blocked", "blocked")],
                        default="active",
                        max_length=255,
                    ),
                ),
                ("status_reason", models.TextField(null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
